name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get docker tag
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            echo ::set-output name=DOCKER_TAG::main
          else
            echo ::set-output name=DOCKER_TAG::${GITHUB_REF#refs/tags/}
          fi

      - name: print info
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
          echo $DOCKER_TAG
        env:
          SOURCE_NAME: ${{ steps.git.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.git.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.git.outputs.SOURCE_TAG }}
          DOCKER_TAG: ${{ steps.git.outputs.DOCKER_TAG }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mtand/sqlite:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Extract tag and tag
        run: |
          set -e -x
          TAG=$(grep -Po 'debian:stable-\K.*(?=-slim)' Dockerfile)
          git tag $TAG || echo "Existing tag"
          git push origin $TAG || echo "tag exists"
