name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "**"

  workflow_dispatch:

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ secrets.OWNER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.5.0
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get docker tag
        id: git
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            echo ::set-output name=DOCKER_TAG::latest
          else
            echo ::set-output name=DOCKER_TAG::${GITHUB_REF#refs/tags/}
          fi
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.5.0
        with:
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: mtand/sqlite:${{ steps.git.outputs.DOCKER_TAG }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Extract tag and tag
        run: |
          set -e -x
          TAG=$(grep -Po 'debian:stable-\K.*(?=-slim)' Dockerfile)
          git tag $TAG || echo "Existing tag"
          git push origin $TAG || echo "tag exists"
